-- Grievance Cleanup and ID Reset Script
-- Location: supabase/grievance_cleanup.sql
--
-- 🎯 Objective:
-- Safely purge all grievance data (test submissions) and reset the ID sequence back to 0001
-- to start fresh in production. All other tables (users, events, news) remain untouched.
--
-- ⚠️ IMPORTANT INSTRUCTIONS:
-- 1. Backup your database before running any script.
-- 2. Run this script in the Supabase SQL Editor.
-- 3. Remember to empty the 'grievance-attachments' Storage Bucket in the Supabase Dashboard.

BEGIN;

-- =========================================================================
-- 1. CLEAN UP GRIEVANCE TABLES (Sub-tables first, then parent table)
-- =========================================================================
-- NOTICE: Deleting grievance data...

-- A. Delete all grievance attachments
TRUNCATE TABLE public.grievance_attachments CASCADE;

-- B. Delete all grievance timeline entries (remarks, status updates)
TRUNCATE TABLE public.grievance_timeline CASCADE;

-- C. Delete the grievances themselves
TRUNCATE TABLE public.grievances CASCADE;


-- =========================================================================
-- 2. RESET SEQUENTIAL ID COUNTER
-- =========================================================================
-- NOTICE: Resetting grievance ID sequence...

-- This resets the sequence generator back to 1.
-- The next submitted grievance display_id will start fresh from 0001.
ALTER SEQUENCE IF EXISTS public.grievance_id_seq RESTART WITH 1;


-- =========================================================================
-- 3. REMOVE GRIEVANCE-RELATED NOTIFICATIONS (Optional but recommended)
-- =========================================================================
-- NOTICE: Removing grievance-related notifications...

-- This deletes any notification generated by test grievances to avoid broken links in the app.
DELETE FROM public.notifications 
WHERE action_path LIKE '/services/grievances/%' 
   OR action_path LIKE '/admin/grievances/%';


-- =========================================================================
-- 4. VERIFICATION
-- =========================================================================
DO $$
DECLARE
    g_count INT;
    gt_count INT;
    ga_count INT;
    n_count INT;
    seq_val BIGINT;
BEGIN
    SELECT COUNT(*) INTO g_count FROM public.grievances;
    SELECT COUNT(*) INTO gt_count FROM public.grievance_timeline;
    SELECT COUNT(*) INTO ga_count FROM public.grievance_attachments;
    SELECT COUNT(*) INTO n_count FROM public.notifications WHERE action_path LIKE '%grievances%';
    
    -- Check sequence current value
    SELECT last_value INTO seq_val FROM public.grievance_id_seq;

    RAISE NOTICE 'Verification results:';
    RAISE NOTICE '- Grievances remaining: %', g_count;
    RAISE NOTICE '- Timeline entries remaining: %', gt_count;
    RAISE NOTICE '- Attachments metadata remaining: %', ga_count;
    RAISE NOTICE '- Grievance notifications remaining: %', n_count;
    RAISE NOTICE '- Next sequence ID starts at: 1 (Current sequence last_value: %)', seq_val;
END $$;

COMMIT;
